name: falr
channels:
  - defaults
  - pytorch
  - comet_ml
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.0
  - numpy=1.18
  - pandas=1.0
  - seaborn=0.10
  - pytorch=1.4.0
  - torchvision=0.5.0
  - fire=0.2
  - tqdm==4.43
  - comet_ml==3.1
  - scikit-learn==0.22
  - papermill==2.0
  - pip:
      - wandb==0.8
      - yaml==5.3
